
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx playwright install
    - run: npm start &
      env:
        CI: true
    - name: Start backend server
      run: |
        cd server
        node server.js &
        cd ..
    - name: Wait for the server to be ready
      run: npx wait-on https://book-library-b0d9.onrender.com/
    - name: Run tests
      run: npm test

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_test
    
    steps:
    - name: Deploy to Render (Backend)
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        wait_deploy: true 

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Deploy to Render (Frontend)
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_STATIC_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_STATIC_API_KEY }}
        wait_deploy: true


