
name: Build and Test

on:

  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx playwright install
    - name: Start backend server
      run: |
        cd server
        node server.js &
        cd ..
    - run: npm start &
      env:
        CI: true

    - name: Wait for the server to be ready
      run: npx wait-on http://localhost:3000 --timeout 60000
    - name: Run tests
      run: npm test

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_test
    
    steps:
    - name: Deploy to Render (Backend)
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        wait_deploy: true 

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: deploy_backend

    steps:
    - name: Deploy to Render (Frontend)
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_STATIC_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_STATIC_API_KEY }}
        wait_deploy: true


