
name: Build and Test

on:

  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install package.json dependencies
      run: npm install

    - name: Replace the config settings
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js

    - name: Start BackEnd
      run: npm run start-be &
    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Install Playwright browsers
      run: npx playwright install


    - name: Wait for the server to be ready
      run: npx wait-on http://localhost:3000 

    - name: Execute Playwright UI tests
      run: npm run test-ui

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_test
    
    steps:
    - name: Deploy to Render (Backend)
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        wait_deploy: true 

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: deploy_backend

    steps:
    - name: Deploy to Render (Frontend)
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_STATIC_SERVICE_ID }}
        api_key: ${{ secrets.LIBRARY_STATIC_API_KEY }}
        wait_deploy: true


